development:
    adapter: mysql2
    database: sharetribe_development
    encoding: utf8
    username: # ADD DATABASE USERNAME
    password: # ADD DATABASE PASSWORD
    host: localhost

cucumber:
  <<: *test
